version: '3.4'

services:
  dsr_translations_db:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_translations_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  dsr_translations_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_translations_net
    volumes:      
      - ~/.docker-conf/redis/data/:/data

  dsr_translations_api:
    ports:
      - "10000:80"
    networks:
      - shared_translations_net
    env_file:
      - env.api

networks:
  shared_translations_net:
    name: dsr_course_project_translations
    driver: bridge